"""
One-off asset-extraction script: samples the Tech Potam logo PNG into two
normalized point clouds (icon monogram, wordmark), classified by brand color
(mint vs graphite). Not part of the shipped app — run manually to regenerate
src/components/LogoMorph/logoData.ts if the source logo ever changes.

Usage: python3 scripts/extract-logo-points.py <path-to-logo.png> <out-ts-path>
"""
import sys
from PIL import Image

SRC = sys.argv[1] if len(sys.argv) > 1 else "/Users/techpotam/Downloads/Tech Potam-02.png"
OUT = sys.argv[2] if len(sys.argv) > 2 else "logoData.ts"

img = Image.open(SRC).convert("RGBA")


def tight_bbox(im, alpha_thresh=20, step=2):
    w, h = im.size
    px = im.load()
    minx, miny, maxx, maxy = w, h, 0, 0
    found = False
    for y in range(0, h, step):
        for x in range(0, w, step):
            if px[x, y][3] > alpha_thresh:
                found = True
                if x < minx: minx = x
                if x > maxx: maxx = x
                if y < miny: miny = y
                if y > maxy: maxy = y
    if not found:
        return (0, 0, w, h)
    return (minx, miny, maxx + 1, maxy + 1)


# Full-logo bbox, then split icon (top) from wordmark (bottom) at the widest
# fully-transparent row gap between them.
full_box = tight_bbox(img)
crop = img.crop(full_box)
cw, ch = crop.size
px = crop.load()

row_has_content = []
for y in range(ch):
    has = any(px[x, y][3] > 20 for x in range(0, cw, 3))
    row_has_content.append(has)

gaps = []
in_gap = False
gap_start = 0
for y, has in enumerate(row_has_content):
    if not has and not in_gap:
        in_gap, gap_start = True, y
    elif has and in_gap:
        gaps.append((gap_start, y))
        in_gap = False
gaps = [g for g in gaps if 0 < g[0] < ch - 1]
split_y = max(gaps, key=lambda g: g[1] - g[0])[0] if gaps else ch // 2

icon_im = crop.crop((0, 0, cw, split_y))
word_im = crop.crop((0, split_y, cw, ch))


def classify(r, g, b):
    return "mint" if (g > r + 18 and g > b + 25) else "graphite"


def sample_region(im, target_long_edge):
    bbox = tight_bbox(im)
    sub = im.crop(bbox)
    w, h = sub.size
    if w >= h:
        new_w, new_h = target_long_edge, max(1, round(h * (target_long_edge / w)))
    else:
        new_h, new_w = target_long_edge, max(1, round(w * (target_long_edge / h)))
    small = sub.resize((new_w, new_h), Image.NEAREST)
    spx = small.load()
    pts = []
    mint_samples, graphite_samples = [], []
    for y in range(new_h):
        for x in range(new_w):
            r, g, b, a = spx[x, y]
            if a < 140:
                continue
            group = classify(r, g, b)
            nx = x / (new_w - 1) if new_w > 1 else 0.5
            ny = y / (new_h - 1) if new_h > 1 else 0.5
            pts.append((round(nx, 4), round(ny, 4), 0 if group == "mint" else 1))
            (mint_samples if group == "mint" else graphite_samples).append((r, g, b))
    aspect = new_w / new_h

    def avg(samples):
        if not samples:
            return None
        n = len(samples)
        return tuple(round(sum(c[i] for c in samples) / n) for i in range(3))

    return pts, round(aspect, 4), avg(mint_samples), avg(graphite_samples)


icon_pts, icon_aspect, icon_mint, icon_graphite = sample_region(icon_im, 56)
word_pts, word_aspect, word_mint, word_graphite = sample_region(word_im, 175)

mint_hex = "#%02x%02x%02x" % (icon_mint or word_mint)
graphite_hex = "#%02x%02x%02x" % (icon_graphite or word_graphite)


def pack(pts):
    flat = []
    for x, y, c in pts:
        flat.extend([x, y, c])
    return ",".join(str(v) for v in flat)


ts = f"""// AUTO-GENERATED by scripts/extract-logo-points.py from the Tech Potam brand
// logo PNG — do not hand-edit. Regenerate if the source logo changes.
//
// Each point cloud is a flat [x, y, colorGroup, x, y, colorGroup, ...] array,
// x/y normalized to [0, 1] within that shape's own tight bounding box,
// colorGroup: 0 = mint, 1 = graphite. Sampled directly from the logo's real
// pixels, so proportions match the brand asset exactly.

export const ICON_ASPECT = {icon_aspect}; // width / height
export const WORDMARK_ASPECT = {word_aspect};

export const MINT = "{mint_hex}";
export const GRAPHITE = "{graphite_hex}";

// eslint-disable-next-line @typescript-eslint/no-loss-of-precision
export const ICON_POINTS: number[] = [{pack(icon_pts)}];

export const WORDMARK_POINTS: number[] = [{pack(word_pts)}];
"""

with open(OUT, "w") as f:
    f.write(ts)

print(f"icon points: {len(icon_pts)}  wordmark points: {len(word_pts)}")
print(f"mint={mint_hex} graphite={graphite_hex}")
print(f"wrote {OUT}")
